# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b92477b04e7e6dccc1fa2cc75895bfd1"
name = "Image Lift"
application_url = "https://imagelift.173.212.233.194.sslip.io"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://imagelift.173.212.233.194.sslip.io/auth/callback",
  "https://imagelift.173.212.233.194.sslip.io/auth/shopify/callback",
  "https://imagelift.173.212.233.194.sslip.io/api/auth/callback"
]

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://imagelift.173.212.233.194.sslip.io/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://imagelift.173.212.233.194.sslip.io/webhooks/compliance"

[[webhooks.subscriptions]]
topics = [ "products/create" ]
uri = "https://imagelift.173.212.233.194.sslip.io/webhooks/products/create"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
